mtgtournament/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tournament.urls')),
    path('admin/', admin.site.urls),
]

tournament/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = "tournament"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:tournament_id>', views.detail, name='detail'),
    path('edit/<int:round_id>', views.edit_round, name='edit_round'),
    path('undo/<int:round_id>', views.undo_round, name='undo_round'),
    path('drop/<int:player_id>', views.drop_player, name='drop_player'),
]

tournament/models.py
from django.db import models
import random

class Player(models.Model):
    tournament = models.ForeignKey("Tournament", on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    opponents = models.ManyToManyField("self")
    # Tiebreakers
    # match points
    # opp MW%
    # GW%
    # opp GW%
    match_points = models.SmallIntegerField(default=0)
    game_points = models.SmallIntegerField(default=0)
    games_played = models.SmallIntegerField(default=0)
    bye_count = models.SmallIntegerField(default=0)
    opponent_match_win_percentage = models.FloatField(default=100/3)
    opponent_game_win_percentage = models.FloatField(default=100/3)
    game_win_percentage = models.FloatField(default=100/3)
    sort_key = models.CharField(max_length=200)
    match_wins = models.SmallIntegerField(default=0)
    match_draws = models.SmallIntegerField(default=0)
    match_losses = models.SmallIntegerField(default=0)
    dropped = models.BooleanField(default=False)
    #next is adding penalties

    def result_display(self):
        return f"{self.match_wins}-{self.match_draws}-{self.match_losses}"

    def match_win_percentage(self):
        if self.opponents.count() == 0:
            return 100/3
        else:
            return max(100/3, (self.match_points - self.bye_count*3)/(self.opponents.count()*3.0)*100)

    def update_opponent_tiebreakers(self):
        value = 0.0;
        for opp in self.opponents.all():
            value += opp.match_win_percentage()
        if self.opponents.count() == 0:
            self.opponent_match_win_percentage = 100/3
        else:
            self.opponent_match_win_percentage = max(100/3, value/self.opponents.count())

        value = 0.0
        for opp in self.opponents.all():
            value += opp.game_win_percentage
        if self.opponents.count() == 0:
            self.opponent_game_win_percentage = 100/3
        else:
            self.opponent_game_win_percentage = max(100/3, value/self.opponents.count())
        self.save()

    def record_result(self, other, wins, draws, games):
        self.opponents.add(other);
        if wins > games - wins - draws:
            self.match_points += 3;
            self.match_wins += 1;
        elif wins == games - wins - draws:
            self.match_points += 1;
            self.match_draws += 1;
        else:
            self.match_losses += 1;
        self.game_points += 3*wins + draws
        self.games_played += games
        self.game_win_percentage = max(100/3, self.game_points/(self.games_played*3.0)*100)
        self.save()

class Table(models.Model):
    number = models.SmallIntegerField()
    current_round = models.ForeignKey("Round", on_delete=models.CASCADE)
    player_a = models.ForeignKey("Player", on_delete=models.CASCADE, related_name="+")
    player_b = models.ForeignKey("Player", on_delete=models.CASCADE, related_name="+")
    good_match = models.BooleanField(default=True)
    reported = models.BooleanField(default=False)
    player_a_wins = models.SmallIntegerField(default=0)
    player_b_wins = models.SmallIntegerField(default=0)
    draws = models.SmallIntegerField(default=0)
    
    def winner(self):
        if self.reported and self.player_a_wins > self.player_b_wins:
            return "a"
        elif self.reported and self.player_b_wins > self.player_a_wins:
            return "b"
        else:
            return ""

class Round(models.Model):
    number = models.SmallIntegerField()
    tournament = models.ForeignKey("Tournament", on_delete=models.CASCADE)
    player_list = models.ManyToManyField("Player")
    all_good = models.BooleanField(default=True)
    completed = models.BooleanField(default=False)
    bye = models.ForeignKey("Player", on_delete=models.CASCADE, related_name="+", null=True)

    def initialize(self, player_list):
        key_strings = ["a"*x for x in range(len(player_list))]
        for p in player_list:
            c = random.choice(key_strings)
            key_strings.remove(c)
            p.sort_key = f"{p.match_points}{c}"
            p.save()
            self.player_list.add(p)
        table_index = 1
        sorted_players = self.player_list.order_by("-sort_key")
        for i in range(1,len(sorted_players),2):
            t = Table(number=table_index, current_round=self, player_a=sorted_players[i-1], player_b=sorted_players[i], good_match=not(sorted_players[i-1] in sorted_players[i-1].opponents.all()))
            self.all_good = self.all_good and t.good_match
            t.save()
            table_index += 1
        if len(sorted_players)%2 == 1:
            self.bye = sorted_players.last()
        self.save()

    def all_good_check(self):
        if not self.completed:
            self.all_good = True
            for table in self.table_set.all():
                table.good_match = not(table.player_a in table.player_b.opponents.all())
                self.all_good = self.all_good and table.good_match
                table.save()
            self.save()
        return self.all_good

    def all_done_check(self):
        for table in self.table_set.all():
            if not(table.reported):
                return False
        return True

    def update_player_standings(self):
        #record_result(self, other, wins, draws, games):
        if self.bye is not None:
            self.bye.match_points += 3
            self.bye.bye_count += 1
            self.bye.match_wins += 1
            self.bye.save()
        for table in self.table_set.all():
            table.player_a.record_result(table.player_b, table.player_a_wins, table.draws, table.player_a_wins+table.player_b_wins+table.draws)
            table.player_b.record_result(table.player_a, table.player_b_wins, table.draws, table.player_a_wins+table.player_b_wins+table.draws)
        #update_opponent_tiebreakers(self):
        for p in self.player_list.all():
            p.update_opponent_tiebreakers()
        
    def uncomplete_round(self):
        if self.bye is not None:
            self.bye.match_points -= 3
            self.bye.bye_count -= 1
            self.bye.save()
        for table in self.table_set.all():
            table.player_a.opponents.remove(table.player_b)
            if table.player_a_wins > table.player_b_wins:
                table.player_a.match_points -= 3
                table.player_a.match_wins -= 1
            elif table.player_a_wins == table.player_b_wins:
                table.player_a.match_points -= 1
                table.player_a.match_draws -= 1
            else:
                table.player_a.match_losses -= 1
            table.player_a.game_points -= 3*table.player_a_wins + table.draws
            table.player_a.games_played -= table.player_a_wins + table.player_b_wins + table.draws
            if table.player_a.games_played > 0:
                table.player_a.game_win_percentage = max(100/3, table.player_a.game_points/(table.player_a.games_played*3.0)*100)
            else:
                table.player_a.game_win_percentage = 100/3
            table.player_a.save()
            
            table.player_b.opponents.remove(table.player_a)
            if table.player_b_wins > table.player_a_wins:
                table.player_b.match_points -= 3
                table.player_b.match_wins -= 1
            elif table.player_a_wins == table.player_b_wins:
                table.player_b.match_points -= 1
                table.player_b.match_draws -= 1
            else:
                table.player_b.match_losses -= 1
            table.player_b.game_points -= 3*table.player_b_wins + table.draws
            table.player_b.games_played -= table.player_a_wins + table.player_b_wins + table.draws
            if table.player_b.games_played > 0:
                table.player_b.game_win_percentage = max(100/3, table.player_b.game_points/(table.player_b.games_played*3.0)*100)
            else:
                table.player_b.game_win_percentage = 100/3
            table.player_b.save()
        self.completed = False
        self.save()

class Tournament(models.Model):
    name = models.CharField(max_length=200)
    player_name_space = models.SmallIntegerField(default=0)
    last_modified = models.DateTimeField(auto_now=True)

    def register(self, name):
        p = Player(name=name, tournament=self)
        p.save()
        if len(name)+1 > self.player_name_space:
            self.player_name_space = len(name) + 1
            self.save()

    def start_next_round(self):
        r = Round(number=Round.objects.filter(tournament=self).count()+1,tournament=self)
        r.save()
        r.initialize(self.player_set.filter(dropped=False))
        r.save()
        return r

tournament/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Tournament, Round, Table, Player
import os


def index(request):
    if "player_names" in request.POST:
        player_names = request.POST["player_names"].split(os.linesep)
        t = Tournament(name=request.POST["t_name"])
        t.save()
        for pn in player_names:
            t.register(pn)
        t.start_next_round()
        return HttpResponseRedirect(reverse("tournament:detail", args=(t.id,)))
    context = {"tour_list":Tournament.objects.all().order_by("-last_modified")}
    return render(request, 'tournament/index.html', context)

def detail(request, tournament_id):
    t = Tournament.objects.get(pk=tournament_id)
    r = Round.objects.get(number=Round.objects.filter(tournament=t).count(),tournament=t)
    if "table_edit" in request.POST:
        if int(request.POST["table_edit"]) >= 0:
            table = Table.objects.get(pk=request.POST["table_edit"])
            table.player_a_wins = request.POST[request.POST["table_edit"]+"a"]
            table.draws = request.POST[request.POST["table_edit"]+"d"]
            table.player_b_wins = request.POST[request.POST["table_edit"]+"b"]
            table.reported = True
            table.save()
        elif r.all_done_check() and not r.completed:
            r.update_player_standings()
            r.completed = True
            r.save()
        elif r.completed:
            r = t.start_next_round()


    context = {"tour_name":t.name, "tour_id":t.id, "round":r, "pairings":r.table_set.order_by("number")}
    if r.completed:
        context["stand_name"] = "as of the current round"
        context["standings"] = r.player_list.order_by("dropped","-match_points","-opponent_match_win_percentage","-game_win_percentage","-opponent_game_win_percentage")
    elif r.number > 1:
        context["stand_name"] = "as of the previous round"
        context["standings"] = Round.objects.get(number=r.number-1).player_list.order_by("dropped","-match_points","-opponent_match_win_percentage","-game_win_percentage","-opponent_game_win_percentage")
    return render(request, 'tournament/detail.html', context)
    
def edit_round(request, round_id):
    r = Round.objects.get(pk=round_id)
    if "choices" in request.POST:
        c = request.POST["choices"].split()
        if c[0] == "BYE":
            t2 = Table.objects.get(pk=c[1][:-1])
            p1 = r.bye
            if c[1][-1] == "a":
                r.bye = t2.player_a
                t2.player_a = p1
            else:
                r.bye = t2.player_b
                t2.player_b = p1
            r.save()
            t2.save()
        elif c[1] == "BYE":
            t1 = Table.objects.get(pk=c[0][:-1])
            p1 = r.bye
            if c[0][-1] == "a":
                r.bye = t1.player_a
                t1.player_a = p1
            else:
                r.bye = t1.player_b
                t1.player_b = p1
            r.save()
            t1.save()
        else:
            t1 = Table.objects.get(pk=c[0][:-1])
            t2 = Table.objects.get(pk=c[1][:-1])
            if c[0][-1] == "a":
                p1 = t1.player_a
                if c[1][-1] == "a":
                    t1.player_a = t2.player_a
                    t2.player_a = p1
                else:
                    t1.player_a = t2.player_b
                    t2.player_b = p1
            else:
                p1 = t1.player_b
                if c[1][-1] == "a":
                    t1.player_b = t2.player_a
                    t2.player_a = p1
                else:
                    t1.player_b = t2.player_b
                    t2.player_b = p1
            t1.save()
            t2.save()
        r.all_good_check()
        
    context = {"round":r, "pairings":r.table_set.order_by("number")}
    return render(request, 'tournament/edit_round.html', context)

def undo_round(request, round_id):
    r = Round.objects.get(pk=round_id)
    r.uncomplete_round()
    return HttpResponseRedirect(reverse("tournament:detail", args=(r.tournament.id,)))
    
def drop_player(request, player_id):
    p = Player.objects.get(pk=player_id)
    p.dropped = not p.dropped
    p.save()
    return HttpResponseRedirect(reverse("tournament:detail", args=(p.tournament.id,)))

tournament/templates/tournament/detail.html
{% load static %}
<head>
    <title>MTG Tournament</title>
	<link href="{% static 'styles.css' %}" type="text/css" rel="stylesheet"></link>
	<script>
		function doEdit(table_number) {
			//hide the table currently being edited
			currentEdit = document.getElementById("hdnTable").value;
			if(currentEdit >= 0) {
				lst = document.getElementsByClassName("edit"+currentEdit);
				for(let i = 0; i < lst.length; i++) {
					lst[i].style.display = "none";
				}
				lst = document.getElementsByClassName("static"+currentEdit);
				for(let i = 0; i < lst.length; i++) {
					lst[i].style.display = "";
				}
			}
			//reveal the new things
			lst = document.getElementsByClassName("edit"+table_number);
			for(let i = 0; i < lst.length; i++) {
				lst[i].style.display = "";
			}
			lst = document.getElementsByClassName("static"+table_number);
			for(let i = 0; i < lst.length; i++) {
				lst[i].style.display = "none";
			}
			document.getElementById("hdnTable").value = table_number;
		}
		
		function cancelEdit(table_number) {
			lst = document.getElementsByClassName("edit"+table_number);
			for(let i = 0; i < lst.length; i++) {
				lst[i].style.display = "none";
			}
			lst = document.getElementsByClassName("static"+table_number);
			for(let i = 0; i < lst.length; i++) {
				lst[i].style.display = "";
			}
			document.getElementById("hdnTable").value = -1;
		}
	</script>
</head>
<body>
	<h1>{{ tour_name }}</h1>
	<div><a href="{% url 'tournament:index' %}">Home</a></div>
	<form method="post" action="{% url 'tournament:detail' tour_id %}"  id="frmMain">
		{% csrf_token %}
		<input type="hidden" name="table_edit" id="hdnTable" value="-1" />
		<h2>Round {{ round.number }}</h2>
		<h3>Pairings</h3>
		{% if not round.all_good_check %}
		<h2 style="background-color:red">Bad Pairings Exist <a href="{% url 'tournament:edit_round' round.id %}">Edit Pairings</a></h2>
		{% endif %}
		<table class='pairings'>
			<tr>
				<th>#</th>
				<th></th>
				<th colspan=3>Results</th>
			</tr>
			{% for table in pairings %}
			<tr {% if not table.good_match %}style="background-color:red"{% endif %}>
				<td>{{ table.number }}</td>
				<td><div>{{ table.player_a.name }}</div><div>{{ table.player_a.result_display }}</div></td>
				<td>
					<span class="static{{ table.id }}">{{ table.player_a_wins }}</span>
					<input style="display:none" class="edit{{ table.id }}" type="number" name="{{ table.id }}a" value="{{ table.player_a_wins }}" />
				</td>
				<td>
					<span class="static{{ table.id }}">{{ table.draws }}</span>
					<input style="display:none" class="edit{{ table.id }}" type="number" name="{{ table.id }}d" value="{{ table.draws }}" />
				</td>
				<td>
					<span class="static{{ table.id }}">{{ table.player_b_wins }}</span>
					<input style="display:none" class="edit{{ table.id }}" type="number" name="{{ table.id }}b" value="{{ table.player_b_wins }}" />
				</td>
				<td><div>{{ table.player_b.name }}</div><div>{{ table.player_b.result_display }}</div></td>
				{% if not round.completed %}
				<td>
					<input type="button" onclick="doEdit({{ table.id }})" value="Edit" class="static{{ table.id }}" />
					<input type="button" value="Cancel" onclick="cancelEdit({{ table.id }})" class="edit{{ table.id }}" style="display:none" />
					<input type="submit" value="Submit" class="edit{{ table.id }}" style="display:none" />
				</td>
				{% endif %}
			</tr>
			{% endfor %}
			{% if round.bye is not None %}
			<tr>
				<td>BYE</td>
				<td><div>{{ round.bye.name }}</div><div>{{ round.bye.result_display }}</div></td>
			</tr>
			{% endif %}
		</table>
		{% if round.all_done_check %}<div style="margin-top:10px"><input type="submit" value="{% if round.completed %}Next Round{% else %}Complete Round{% endif %}" /></div>{% endif %}
	</form>
	{% if stand_name %}
	<h3> Standings {{ stand_name }}</h3>
	<table>
		<tr>
			<th></th>
			<th>Player</th>
			<th>MP</th>
			<th>OMW%</th>
			<th>GW%</th>
			<th>OGW%</th>
		</tr>
		{% for player in standings %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td><span {% if player.dropped %}style="text-decoration:line-through"{% endif %}>{{ player.name }}</span></td>
			<td>{{ player.match_points }}</td>
			<td>{{ player.opponent_match_win_percentage|floatformat:2 }}</td>
			<td>{{ player.game_win_percentage|floatformat:2 }}</td>
			<td>{{ player.opponent_game_win_percentage|floatformat:2 }}</td>
			<td>
				<form method="post" action="{% url 'tournament:drop_player' player.id %}">
					{% csrf_token %}
					<input type="submit" value="{% if player.dropped %}Undrop{% else %}Drop{% endif %}" />
				</form>
			</td>
		</tr>
		{% endfor %}
	</table>
	{% endif %}
	{% if round.completed %}
	<form method="post" action="{% url 'tournament:undo_round' round.id %}">
		{% csrf_token %}
		<input type="submit" value="Undo Complete" />
	</form>
	{% endif %}
</body>

tournament/templates/tournament/edit_round.html
{% load static %}
<head>
    <title>MTG Tournament</title>
	<link href="{% static 'styles.css' %}" type="text/css" rel="stylesheet"></link>
	<script>
		function doSubmit() {
			var count = 0;
			var lst = document.getElementsByClassName("choices");
			var txt = document.getElementById("hdnChoices");
			for(let i = 0; i < lst.length; i++) {
				if(lst[i].checked) {
					if(count > 0) {
						txt.value += " ";
					}
					txt.value += lst[i].id;
					count++;
				}
			}
			if(count == 2) {
				document.getElementById("frmMain").submit();
			} else {
				txt.value = "";
			}
		}
	</script>
</head>
<body>
	<h1>{{ round.tournament.name }}</h1>
	<form method="post" action="{% url 'tournament:edit_round' round.id %}"  id="frmMain">
		{% csrf_token %}
		<input type="hidden" name="choices" id="hdnChoices" value="" />
		<h2>Round {{ round.number }}</h2>
		<h3>Pairings</h3>
		{% if not round.all_good_check %}<h2 style="background-color:red">Bad Pairings Exist</h2>{% endif %}
		<table class="all-borders">
			<tr>
				<th>#</th>
				<th></th>
				<th colspan=3>Results</th>
			</tr>
			{% for table in pairings %}
			<tr {% if not table.good_match %}style="background-color:red"{% endif %}>
				<td>{{ table.number }}</td>
				<td><div>{{ table.player_a.name }}</div><div>{{ table.player_a.result_display }}</div></td>
				<td><input type="checkbox" class="choices" id="{{ table.id }}a" /></td>
				<td><div>{{ table.player_b.name }}</div><div>{{ table.player_b.result_display }}</div></td>
				<td><input type="checkbox" class="choices" id="{{ table.id }}b" /></td>
			</tr>
			{% endfor %}
			{% if round.bye is not None %}
			<tr>
				<td>BYE</td>
				<td><div>{{ round.bye.name }}</div><div>{{ round.bye.result_display }}</div></td>
				<td><input type="checkbox" class="choices" id="BYE"/></td>
			</tr>
			{% endif %}
		</table>
		<div style="margin-top:10px"><input type="button" onclick="doSubmit()" value="Submit" /></div>
		<div style="margin-top:10px"><a href="{% url 'tournament:detail' round.tournament.id %}">Back to Event</a></div>
	</form>
</body>

tournament/templates/tournament/index.html
{% load static %}
<head>
    <title>MTG Tournament</title>
	<link href="{% static 'styles.css' %}" type="text/css" rel="stylesheet"></link>
</head>
<body>
	<h1>MTG Tournament</h1>
	<form method="post">
		{% csrf_token %}
		<h2>Create New Tournament</h2>
		<div>Name: <input type="text" name="t_name" /></div>
		<div>Players:</div>
		<div><textarea name="player_names" rows="40" cols="100"></textarea></div>
		<div style="margin-top:10px"><input type="submit" value="Create" /></div>
	</form>
		<h2>Open Existing Tournament</h2>
		{% if tour_list %}
		<table>
		{% for t in tour_list %}
			<tr>
				<td><a href="{% url 'tournament:detail' t.id %}">{{ t.name }}</a></td>
				<td>{{ t.last_modified }}</td>
			</tr>
		{% endfor %}
		</table>
		{% endif %}
</body>